### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by TheBitcoinBaron** [Zhincore/cp2077-sfx-map#1]
Title? I open this in notepad++ and it's all red and pretty unreadable anyhow.

**Comment by Zhincore** [comment]
Hey, sorry for the late reply, I haven't noticed your issue!
What do you mean red? It's a JSON, which is more of a machine-readbale format, but you can simply use the search function in Notepad, search for keyword you want to find and if you're lucky, the name of opuspak / wem pops up and you can proceed from there. 
There are more user-friendly applications out here like [SoundFX Search and Update](https://www.nexusmods.com/cyberpunk2077/mods/11075), that might work for you better!
